### PR TITLE
macOS and logging fixes

### PR DESCRIPTION
**Pull request by maleadt**
Requires / fixes compatibility with https://github.com/JuliaGPU/CUDAapi.jl/pull/41

Fixes https://github.com/JuliaGPU/CUDAdrv.jl/issues/99

Replaces https://github.com/JuliaGPU/CUDAapi.jl/pull/40

### CODE REVIEW

**Comment by maleadt** [comment]
@sbromberger @DennisRutjes @jekbradbury this should fix issues with CUDAdrv/CUDAapi on macOS with Julia 0.6. could you verify? If OK, I'll tag a new version.

**Comment by DennisRutjes** [comment]
Hi @maleadt thanks for addressing this issue!

However I checked the release-0.6 branch out and tried to build this in my source 0.6.2 build.
Maybe I am doing things wrong ?

```
Pkg.clone("CUDAdrv")
INFO: Cloning CUDAdrv from git://github.com/JuliaGPU/CUDAdrv.jl.git
INFO: Computing changes...
WARNING: julia is fixed at 0.6.2 conflicting with requirement for CUDAdrv: [0.7.0-,∞)
INFO: No packages to install, update or remove
INFO: Package database updated

Pkg.checkout("CUDAdrv","release-0.6")
INFO: Checking out CUDAdrv release-0.6...
WARNING: Cannot perform fast-forward merge.
INFO: Pulling CUDAdrv latest release-0.6...
WARNING: Cannot perform fast-forward merge.
WARNING: julia is fixed at 0.6.2 conflicting with requirement for CUDAdrv: [0.7.0-,∞)
INFO: No packages to install, update or remove

Pkg.build("CUDAdrv")
Pkg.build("CUDAdrv")
INFO: Building CUDAdrv
=========================================================================================[ ERROR: CUDAdrv ]=========================================================================================

LoadError: MethodError: no method matching dlopen(::Void)
Closest candidates are:
  dlopen(::Symbol) at libdl.jl:94
  dlopen(::Symbol, ::Integer) at libdl.jl:94
  dlopen(::AbstractString) at libdl.jl:97
  ...
while loading /Users/drutjes/.julia/v0.6/CUDAdrv/deps/build.jl, in expression starting on line 108

====================================================================================================================================================================================================

==========================================================================================[ BUILD ERRORS ]==========================================================================================

WARNING: CUDAdrv had build errors.

 - packages with build errors remain installed in /Users/drutjes/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("CUDAdrv")`
 - build a single package by running its `deps/build.jl` script

===========================================================================
```

**Comment by maleadt** [comment]
Please use code blocks.

Just `cd` into the CUDAdrv.jl directory, checkout the `release-0.6` branch and do a `git pull`.
If it still fails, please run Julia with `DEBUG` env var set to `true` and post the output.

**Comment by DennisRutjes** [comment]
I will try to get this going on my windows laptop instead of my macbook-pro, maybe I will wait when Julia Integrates more easily with GPU

**Comment by maleadt** [comment]
This is a package manager usability problem because the branch isn't released yet, and has nothing do to with GPU integration. In addition, I don't have a macOS system, so if nobody fixes this or gives me feedback on PRs like this one, integration won't improve.

**Comment by DennisRutjes** [comment]
you have a point there, but it looks like I have not the expertise in Julia to verify your PR. 
I checked out the CUDAdrv (within julia and tried to build it in the REPL) the problem arose with the dlopen method, perhaps I have the wrong DynamicLink library. 
I would like to do the necessary steps to fix this, but the I need some guidance :-)

**Comment by maleadt** [comment]
I'd be happy to help :slightly_smiling_face: 

At this point, I've merged these changed and released them, so a regular `Pkg.update()` should bring CUDAdrv up to date (maybe you'll have to `Pkg.free("CUDAdrv")` first, since you've checked out a specific branch before). Verify you're at v0.7.8 afterwards by inspecting `Pkg.status()`.

Afterwards, `Pkg.build("CUDAdrv")` should work without issue. If not, try `DEBUG=true julia -e 'Pkg.build("CUDAdrv")` and post the output here.

**Comment by jekbradbury** [comment]
Something related to this change https://github.com/JuliaLang/METADATA.jl/pull/14131/files meant that my CUDAdrv was stuck on v0.7.7 until I `Pkg.rm`ed CUDAnative and CuArrays. At that point I was able to install CUDAdrv v0.7.8, but the most recent tagged CUDAnative compatible with Julia 0.6 uses the outdated `@debug` macro:
```
julia> Pkg.add("CUDAdrv")
INFO: Cloning cache of FastClosures from https://github.com/c42f/FastClosures.jl.git
INFO: Cloning cache of MicroLogging from https://github.com/c42f/MicroLogging.jl.git
INFO: Installing CUDAapi v0.4.2
INFO: Installing CUDAdrv v0.7.8
INFO: Installing FastClosures v0.2.0
INFO: Installing MicroLogging v0.2.0
INFO: Building CUDAdrv
INFO: Package database updated

julia> Pkg.add("CUDAnative")
INFO: Installing CUDAnative v0.6.2
INFO: Installing LLVM v0.5.1
INFO: Building LLVM
INFO: LLVM.jl has already been built for this toolchain, no need to rebuild
INFO: Building CUDAdrv
INFO: Building CUDAnative
===========================================================================================[ ERROR: CUDAnative ]============================================================================================

LoadError: UndefVarError: @debug not defined
while loading /Users/james/.julia/v0.6/CUDAnative/deps/build.jl, in expression starting on line 13

============================================================================================================================================================================================================

```

**Comment by maleadt** [comment]
Thanks, I forgot to fix upper bounds on CUDAapi in CUDAnative. Will fix in a moment.

**Comment by maleadt** [comment]
OK, should be fixed with CUDAnative v0.6.3. Unsure about being stuck on an older CUDAapi though.

**Pull request merged**
