### PR TITLE
implement wait on stream

### PR DESCRIPTION
**Pull request by vchuravy**
CC @keno

### CODE REVIEW

**Comment by vchuravy** [comment]
@maleadt any qualms with extending `Base.wait`?

**Comment by maleadt** [comment]
> @maleadt any qualms with extending `Base.wait`?

I'm not sure. Semantics of `Base.wait` are generally a blocking wait on the host, so that would need to be `cuEventSynchronize`. But the wait vs synchronize terminology is a choice by CUDA, so it would be confusing to switch that here (with `Base.wait(::CuEvent) = cuEventSynchronize`). So I guess it's fine?

**Comment by maleadt** [comment]
Yeah I'm not ready to commit to this API, so I removed the extension of `Base.wait`. Specifically, I think it would make more sense to have `Base.wait(::CuEvent)` and `Base.wait(::CuStream)` do the expected thing that is now implemented by `synchronize`, i.e. have the host wait. But then the question is how to make a stream wait; maybe `wait!(::CuStream, ::CuEvent)` (but then we always need to pass a stream)?

**Comment by vchuravy** [comment]
Seems okay, thanks for merging.

**Pull request merged**
