### PR TITLE
Expand usage section in docs

### PR DESCRIPTION
**Pull request by una-dinosauria**
In the spirit of CUDArt's [README](https://github.com/JuliaGPU/CUDArt.jl/blob/master/README.md), which greatly helped me run my first CUDA kernels a couple of years ago.

Related: https://github.com/JuliaGPU/CUBLAS.jl/issues/34

### CODE REVIEW

**Comment by maleadt** [comment]
Thanks for the contribution! Wouldn't it be better to put that content in the documentation instead, ie. [here](http://juliagpu.github.io/CUDAdrv.jl/latest/)? I purposefully stripped the README of any non-trivial information a while ago to avoid duplication between the README and the docs.

**Comment by una-dinosauria** [comment]
Makes sense. I've updated the PR.

**Comment by maleadt** [comment]
Great, thanks. I'll review up close next week (or just push some changes, if you don't mind). I'm not a big fan of the `list of modules` approach of the CUDArt docs...
Also, CI seems confused by this, and I think it will fail doctests (because you removed some trailing semicolons).

**Comment by una-dinosauria** [comment]
`ci.maleadt.net` seems to be down

**Comment by maleadt** [comment]
Does it? Works from here... What IP does it resolve to?

**Comment by una-dinosauria** [comment]
`109.236.138.147`. I get an `ERR_TIMED_OUT` on the browser.

**Comment by maleadt** [comment]
That is the correct IP indeed. Can you try `curl` on ports 80 and 8010? If not, I'll look into it tomorrow.
For now, here's the log of the build failure: https://pastebin.com/xzAUVJNn

**Comment by MikeInnes** [comment]
There seems to be an error running the doctests – you can reproduce it locally with `Pkg.add("Documenter"); Pkg.test("CUDAdrv")`. Taking a quick look now so may be able to fix it.

**Comment by MikeInnes** [comment]
Got it – thanks for the patch!

**Comment by una-dinosauria** [comment]
Thanks @MikeInnes, I was kinda busy the last few days.
@maleadt, I was wondering if you could share what approach you like instead of modules?

**Comment by maleadt** [comment]
> I was wondering if you could share what approach you like instead of modules?

Oh, I just meant the `init`/`mdinit`/`finit`/`mdclose` boilerplate. Looks like smelly code, but I haven't thought about a cleaner replacement.

Also, can you reach my CI now?

**Comment by una-dinosauria** [comment]
Thanks. ci.maleadt.net is reachable for me now.

**Pull request merged**
