### PR TITLE
expose UVM API

### PR DESCRIPTION
**Pull request by vchuravy**
I mocked this up to test how UVM would impact an application.
This is low priority for me so  I won't be spending much time on it.

### CODE REVIEW

**Comment by maleadt** [comment]
I think we need a Buffer type in Base (eg. JuliaLang/julia#12447) before tackling this.

**Comment by vchuravy** [comment]
Yeah it is much less useful if you only use it for GPU memory

**Comment by maleadt** [comment]
Maybe we should make this part of the type, so that CuArray can have an optimized convert to Array that just does unsafe_wrap.
EDIT: or just make CuArray use this all the time.

**Comment by maleadt** [comment]
Rebased.

**Comment by maleadt** [comment]
> Yeah it is much less useful if you only use it for GPU memory

So that turned out to be false, and unified memory is very useful for handling multi-GPU setups.
Let's merge if CI agrees.

**Pull request merged**
