### PR TITLE
Version-bound the test for cuFuncSetAttribute.

### LINKED ISSUE #124: test CUDAdrv failed on Windows 10, CUDA 8.0, device Quadro M2000M
``` julia
(v1.1) pkg> test CUDAdrv
   Testing CUDAdrv
 Resolving package versions...
    Status `C:\Users\P6B8B~1.FAK\AppData\Local\Temp\jl_2CF8.tmp\Manifest.toml`
  [3895d2a7] CUDAapi v0.5.4
  [c5f51814] CUDAdrv v1.0.1
  [2a0f44e3] Base64  [`@stdlib/Base64`]
  [8ba89e20] Distributed  [`@stdlib/Distributed`]
  [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
  [8f399da3] Libdl  [`@stdlib/Libdl`]
  [56ddb016] Logging  [`@stdlib/Logging`]
  [d6f4376e] Markdown  [`@stdlib/Markdown`]
  [de0858da] Printf  [`@stdlib/Printf`]
  [9a3f8284] Random  [`@stdlib/Random`]
  [9e88b42a] Serialization  [`@stdlib/Serialization`]
  [6462fe0b] Sockets  [`@stdlib/Sockets`]
  [8dfed614] Test  [`@stdlib/Test`]
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]
[ Info: Testing using device Quadro M2000M
attributes: Error During Test at C:\Users\***\.julia\packages\CUDAdrv\JWljj\test\execution.jl:88
  Got exception outside of a @test
  CUDA error: invalid argument (code #1, ERROR_INVALID_VALUE)
  Stacktrace:
   [1] macro expansion at C:\Users\***\.julia\packages\CUDAdrv\JWljj\src\base.jl:147 [inlined]
   [2] getindex(::CUDAdrv.AttributeDict, ::CUDAdrv.CUfunction_attribute) at C:\Users\P.Fakcharoenphol\.julia\packages\CUDAdrv\JWljj\src\execution.jl:203
   [3] top-level scope at C:\Users\***\.julia\packages\CUDAdrv\JWljj\test\execution.jl:93
   [4] top-level scope at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Test\src\Test.jl:1083
   [5] top-level scope at C:\Users\***\.julia\packages\CUDAdrv\JWljj\test\execution.jl:90
   [6] top-level scope at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Test\src\Test.jl:1083
   [7] top-level scope at C:\Users\***\.julia\packages\CUDAdrv\JWljj\test\execution.jl:3
   [8] include at .\boot.jl:326 [inlined]
   [9] include_relative(::Module, ::String) at .\loading.jl:1038
   [10] include(::Module, ::String) at .\sysimg.jl:29
   [11] include(::String) at .\client.jl:403
   [12] top-level scope at C:\Users\***\.julia\packages\CUDAdrv\JWljj\test\runtests.jl:36
   [13] top-level scope at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Test\src\Test.jl:1083
   [14] top-level scope at C:\Users\***l\.julia\packages\CUDAdrv\JWljj\test\runtests.jl:29
   [15] top-level scope at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Test\src\Test.jl:1083
   [16] top-level scope at C:\Users\P.Fakcharoenphol\.julia\packages\CUDAdrv\JWljj\test\runtests.jl:7
   [17] include at .\boot.jl:326 [inlined]
   [18] include_relative(::Module, ::String) at .\loading.jl:1038
   [19] include(::Module, ::String) at .\sysimg.jl:29
   [20] include(::String) at .\client.jl:403
   [21] top-level scope at none:0
   [22] eval(::Module, ::Any) at .\boot.jl:328
   [23] exec_options(::Base.JLOptions) at .\client.jl:243
   [24] _start() at .\client.jl:436
Test Summary:       | Pass  Error  Total
CUDAdrv             |   93      1     94
  base              |    5             5
  API wrappers      |   79      1     80
    errors          |    5             5
    version         |    1             1
    devices         |    1             1
    context         |   13            13
    primary context |   11            11
    cache config    |    1             1
    shmem config    |    1             1
    module          |   11            11
    memory          |   15            15
    stream          |    1             1
    execution       |   15      1     16
      attributes    |           1      1
    events          |    4             4
    profile         |              No tests
  gc                |    2             2
  examples          |    1             1
ERROR: LoadError: Some tests did not pass: 93 passed, 0 failed, 1 errored, 0 broken.
in expression starting at C:\Users\***\.julia\packages\CUDAdrv\JWljj\test\runtests.jl:5
ERROR: Package CUDAdrv errored during testing
```

### PR DESCRIPTION
**Pull request by maleadt**
Fix #124

### CODE REVIEW

**Comment by maleadt** [comment]
Strange, `bors` ought to have merged this...

**Comment by vchuravy** [comment]
xD https://github.com/JuliaGPU/CUDAdrv.jl/pull/127#issuecomment-467133449

**Comment by maleadt** [comment]
Oh... right... :man_facepalming: 
CI just happened to start so very close to my initial comment to be believable.

**Pull request merged**
